### ISSUE TITLE
ghc8

### ISSUE THREAD

**Issue by xrchz** [tensor5/haskell-happstack#14]
Can these packages be upgraded to depend on >=ghc-8.0.1?

**Comment by tensor5** [comment]
Last time I checked, there where problems with a lot of packages. I'll try again next weekend.

**Comment by tensor5** [comment]
There are several updates that break `gitit`, such as `http-client-tls` `http-conduit` and `tagsoup`. There are also many packages that have been removed from [haskell-core] after GHC 8, but I can adopt those.

**Comment by tensor5** [comment]
Fixed in c6ff29bfbb7bfeab6d1cff7eff1863fae33b1414.

**Comment by xrchz** [comment]
Thanks for looking into this!

I still have some problems trying to upgrade, specifically because of `haskell-fail` and `haskell-hex`, but I will investigate...

**Comment by xrchz** [comment]
full uninstall and reinstall did the trick
